import Foundation

// Otomatik üretildi (Android ProfileQuestionnaireScreen.questionEn).
let questionEnglish: [String: String] = [
    "Ana hedefin ne?": "What's your main goal?",
    "Programın ve tahmini süren bu hedefe göre hazırlanır.": "Your program and estimated timeline are built around it.",
    "Kilo verme": "Lose weight",
    "Kilo alma": "Gain weight",
    "Kas kazanma": "Build muscle",
    "Formu koruma": "Stay in shape",
    "Bunu neden istiyorsun?": "Why do you want this?",
    "Seni harekete geçiren kişisel nedenini yaz.": "Write the personal reason that drives you.",
    "Seni en çok ne durdurdu?": "What stopped you most?",
    "Sürdürülebilir bir plan için gerçek engeli seç.": "Pick the real obstacle so the plan is sustainable.",
    "Zaman": "Time",
    "Motivasyon": "Motivation",
    "Sakatlık": "Injury",
    "Program eksikliği": "No program",
    "Beslenme": "Nutrition",
    "Daha önce düzenli spor yaptın mı?": "Have you trained regularly before?",
    "Geçmiş deneyimin": "Your past experience",
    "Hayır": "No",
    "Kısa süre": "Briefly",
    "6–12 ay": "6–12 months",
    "1 yıldan fazla": "Over 1 year",
    "Kendini hangi seviyede görüyorsun?": "What level are you?",
    "Yoğunluğu buna göre ayarlarız.": "We set the intensity to match.",
    "Başlangıç": "Beginner",
    "Orta": "Intermediate",
    "İleri": "Advanced",
    "Son 3 ayda haftada kaç gün spor yaptın?": "Days per week you trained in the last 3 months?",
    "Mevcut alışkanlığın": "Your current habit",
    "0 gün": "0 days",
    "1–2 gün": "1–2 days",
    "3–4 gün": "3–4 days",
    "5+ gün": "5+ days",
    "Haftada kaç gün ayırabilirsin?": "How many days a week can you train?",
    "Gerçekçi bir tempo seç.": "Pick a realistic pace.",
    "2 gün": "2 days",
    "3 gün": "3 days",
    "4 gün": "4 days",
    "5 gün": "5 days",
    "6 gün": "6 days",
    "7 gün": "7 days",
    "Bir antrenman için ne kadar süren var?": "How long do you have per workout?",
    "Isınma ve soğuma dahil ayırabileceğin toplam süre.": "Total time including warm-up and cool-down.",
    "15 dk": "15 min",
    "30 dk": "30 min",
    "45 dk": "45 min",
    "60 dk": "60 min",
    "75+ dk": "75+ min",
    "Hangi antrenmanları seversin?": "Which workouts do you enjoy?",
    "Birden fazla seçebilirsin.": "You can pick more than one.",
    "Ağırlık": "Weights",
    "Koşu": "Running",
    "Bisiklet": "Cycling",
    "Vücut ağırlığı": "Bodyweight",
    "Pilates": "Pilates",
    "Mobilite": "Mobility",
    "Barre": "Barre",
    "Düşük etkili": "Low impact",
    "Toparlanma": "Recovery",
    "Nerede çalışacaksın?": "Where will you train?",
    "Egzersizler ortama göre seçilir.": "Exercises are chosen for your setting.",
    "Evde": "At home",
    "Spor salonunda": "At the gym",
    "Açık havada": "Outdoors",
    "Karışık": "Mixed",
    "Hangi ekipmanların var?": "What equipment do you have?",
    "Birden fazla seçebilirsin. “Ekipman yok” tek başına seçilir.": "Pick any that apply. “No equipment” is chosen on its own.",
    "Ekipman yok": "No equipment",
    "Dambıl": "Dumbbells",
    "Direnç bandı": "Resistance band",
    "Barfiks barı": "Pull-up bar",
    "Sehpa": "Bench",
    "Halter": "Barbell",
    "TRX / halka": "TRX / rings",
    "Pilates topu": "Pilates ball",
    "Atlama ipi": "Jump rope",
    "Tam salon": "Full gym",
    "Kardiyo aleti": "Cardio machine",
    "Ağrı veya sakatlık var mı?": "Any pain or injury?",
    "Birden fazla bölge seçebilirsin. “Yok” tek başına seçilir.": "Pick any areas. “None” is chosen on its own.",
    "Yok": "None",
    "Bel": "Lower back",
    "Diz": "Knee",
    "Omuz": "Shoulder",
    "Boyun": "Neck",
    "Diğer": "Other",
    "Gün içinde ne kadar hareketlisin?": "How active are you during the day?",
    "Günlük enerji hesabı": "For your daily energy estimate",
    "Çoğunlukla oturuyorum": "Mostly sitting",
    "Ara sıra hareket": "Occasionally active",
    "Aktif": "Active",
    "Çok aktif": "Very active",
    "Uyku düzenin nasıl?": "How do you sleep?",
    "Toparlanma kapasiten": "Your recovery capacity",
    "5 saatten az": "Under 5 hours",
    "5–6 saat": "5–6 hours",
    "7–8 saat": "7–8 hours",
    "9+ saat": "9+ hours",
    "Koçunun bilmesi gereken başka bir şey?": "Anything else your coach should know?",
    "Tercih, kısıt veya not ekleyebilirsin.": "Add preferences, limits or notes.",
    "Hedefit'in antrenmanlarını adet döngüsü bilgilerine göre uyarlamasını ister misin?": "Would you like Hedefit to adapt your workouts using menstrual cycle information?",
    "İsteğe bağlı. Tek başına antrenman kararı vermez; günlük check-in cevapların her zaman önceliklidir. İstediğin zaman Ayarlar'dan kapatabilir ve verini silebilirsin.": "Optional. It never decides your workout on its own — your daily check-in always comes first. You can turn it off and delete your data in Settings at any time.",
    "Hangi bölgelere odaklanmak istersin?": "Which areas do you want to focus on?",
    "Birden fazla seçebilirsin. Haritadan da dokunabilirsin.": "Pick any that apply. You can also tap the map.",
    "Karın": "Abs",
    "Göğüs": "Chest",
    "Sırt": "Back",
    "Kol": "Arms",
    "Kalça": "Hips",
    "Bacak": "Legs",
    "Genel Gelişim": "Overall",
    "Sağlık durumun hakkında bilgi ver.": "Tell us about your health.",
    "Birden fazla seçebilirsin. “Yok” tek başına seçilir.": "Pick any that apply. “None” is chosen on its own.",
    "Diyabet": "Diabetes",
    "Kalp Hastalığı": "Heart disease",
    "İnsülin Direnci": "Insulin resistance",
    "Hipotiroidi": "Hypothyroidism",
    "Hipertansiyon": "Hypertension",
    "Yüksek Kolesterol": "High cholesterol",
    "Besin alerjin var mı?": "Do you have food allergies?",
    "Gluten": "Gluten",
    "Süt ürünleri": "Dairy",
    "Yumurta": "Eggs",
    "Kuruyemiş": "Nuts",
    "Deniz ürünleri": "Seafood",
    "Soya": "Soy",
    "Beslenme tercihin nedir?": "What is your diet preference?",
    "Beslenme önerilerinde bunu dikkate alırız.": "We take this into account in nutrition suggestions.",
    "Standart": "Standard",
    "Vejetaryen": "Vegetarian",
    "Vegan": "Vegan",
    "Pesketaryen": "Pescatarian",
    "Bu alışkanlıklardan hangisine sahipsin?": "Which of these habits apply to you?",
    "Birden fazla seçebilirsin. “Yok” seçeneği diğerlerini temizler.": "Pick any that apply. “None” clears the others.",
    "Sigara": "Smoking",
    "Alkol": "Alcohol",
    "Gece geç yatıyorum": "I go to bed late",
    "Fazla şeker tüketiyorum": "I eat a lot of sugar",
    "Çok oturuyorum": "I sit a lot",
    "Egzersizi erteliyorum": "I put off exercise",
    "Düzenli beslenemiyorum": "I can't eat regularly",
    "Günlük stres seviyeni nasıl tanımlarsın?": "How would you describe your daily stress?",
    "Toparlanma ihtiyacını planlarken bu bilgiyi de dikkate alırız.": "We take this into account when planning your recovery.",
    "Nadiren stres yaşıyorum": "I rarely feel stressed",
    "Bazen stresli oluyorum": "I'm sometimes stressed",
    "Sık sık stres yaşıyorum": "I'm often stressed",
    "Neredeyse her gün stres altındayım": "I'm stressed almost every day",
    "Mevcut yaşam tarzından ne kadar memnunsun?": "How satisfied are you with your current lifestyle?",
    "Fiziksel performansın nasıl?": "How is your physical performance?",
    "Bilmiyorsan boş bırakabilirsin.": "Leave it blank if you don't know.",
]
