// Single source of raw exercise rows: the RepDB atlas plus the supplement
// (data/exercises-supplement.json, built by scripts/build-exercise-supplement.mjs).
// The atlas file is regenerated by scripts/import-repdb.mjs, so additions live
// in the supplement and are merged here for every consumer.

import atlasData from "../data/exercises.json" with { type: "json" };
import supplementData from "../data/exercises-supplement.json" with { type: "json" };

export const exerciseRecords: unknown[] = [...(atlasData as unknown[]), ...(supplementData as unknown[])];
