// Hand-written Turkish names for every catalog exercise (keyed by the English catalog name).
// Convention: equipment first (Halter, Dambıl, Girya, Kablo, Makine, Smith Makinede, Bantlı, TRX, Halka),
// then the movement name Turkish gym-goers actually use (Squat, Deadlift, Bench Press, Barfiks, Şınav...).
export const catalogExerciseNamesTr: Record<string, string> = {
  "Ab Wheel Rollout": "Karın Tekerleği (Ab Wheel)",
  "Air Bike": "Air Bike (Fanlı Bisiklet)",
  "Archer Pull Ups": "Okçu Barfiks",
  "Archer Push Ups": "Okçu Şınav",
  "Arnold Press": "Dambıl Arnold Press",
  "Machine Assisted Dips": "Makine Destekli Dips",
  "Assisted Pull Ups": "Makine Destekli Barfiks",
  "Back Extension": "Hiperekstansiyon (Bel Sehpası)",
  "Back Lever": "Back Lever (Barda)",
  "Stability Ball Leg Curl": "Pilates Topuyla Leg Curl",
  "Ball Pike": "Pilates Topuyla Pike",
  "Band Assisted Pull Ups": "Bant Destekli Barfiks",
  "Band Pull Apart": "Bantla Pull-Apart",
  "Banded Adductor Stretch": "Bantla İç Bacak Esneme",
  "Banded Ankle Stretch": "Bantla Ayak Bileği Esneme",
  "Banded Calf Stretch": "Bantla Baldır Esneme",
  "Banded Chest Stretch": "Bantla Göğüs Esneme",
  "Banded Clamshell": "Bantlı Clamshell",
  "Banded Figure-4 Stretch": "Bantla 4 Figürü Kalça Esneme",
  "Banded Fire Hydrant": "Bantlı Fire Hydrant",
  "Banded Glute Bridge": "Bantlı Kalça Köprüsü",
  "Banded Good Morning": "Bantlı Good Morning",
  "Banded Hamstring Stretch": "Bantla Arka Bacak Esneme",
  "Banded Hip Thrust": "Bantlı Hip Thrust",
  "Banded IT-Band Stretch": "Bantla IT Bandı Esneme",
  "Banded Kneeling Hip Thrust": "Bantlı Diz Üstü Hip Thrust",
  "Banded Lat Stretch": "Bantla Kanat Esneme",
  "Banded Lateral Walk": "Bantlı Yan Yürüyüş",
  "Banded Rear Delt Stretch": "Bantla Arka Omuz Esneme",
  "Banded Romanian Deadlift": "Bantlı Romanian Deadlift",
  "Banded Seated Hip Abduction": "Bantlı Oturarak Kalça Açma",
  "Banded Shoulder Stretch": "Bantla Omuz Esneme",
  "Banded Squat": "Bantlı Squat",
  "Banded Standing Leg Curl": "Bantlı Ayakta Leg Curl",
  "Banded Standing Hip Abduction": "Bantlı Ayakta Kalça Açma",
  "Banded Standing Hip Adduction": "Bantlı Ayakta Kalça Kapama",
  "Banded Sumo Walk": "Bantlı Sumo Yürüyüş",
  "Banded Terminal Knee Extension": "Bantlı Diz Kilitleme (TKE)",
  "Banded Triceps Stretch": "Bantla Arka Kol Esneme",
  "Barbell Ab Rollout": "Halterle Karın Açma (Rollout)",
  "Barbell Calf Raise": "Halterle Baldır Kaldırma",
  "Barbell Curl": "Halter Biceps Curl",
  "Barbell Front Raise": "Halterle Öne Kaldırma",
  "Barbell Glute Bridge": "Halterle Kalça Köprüsü",
  "Barbell Lunge": "Halter Lunge",
  "Barbell Overhead Extension": "Halter Baş Üstü Triceps Extension",
  "Barbell Preacher Curl": "Halter Preacher Curl",
  "Barbell Pullover": "Halter Pullover",
  "Barbell Rear Delt Row": "Halterle Arka Omuz Kürek Çekiş",
  "Barbell Reverse Lunge": "Halter Geri Lunge",
  "Bent-Over Barbell Row": "Halterle Öne Eğilerek Kürek Çekiş",
  "Barbell Wrist Curl": "Halter Bilek Curl",
  "Battle Rope Double Slam": "Battle Rope Çift Kol Vuruş",
  "Battle Ropes": "Battle Rope Dalgalar",
  "Bear Crawl": "Ayı Yürüyüşü",
  "Behind the Back Barbell Shrug": "Arkadan Halter Shrug",
  "Behind-the-Neck Lat Pulldown": "Ense Arkası Lat Pulldown",
  "Behind the Neck Press": "Ense Arkası Halter Press",
  "Behind-the-Neck Pull-Up": "Ense Arkası Barfiks",
  "Bench Adductor Stretch": "Sehpada İç Bacak Esneme",
  "Bench Ankle Stretch": "Sehpada Ayak Bileği Esneme",
  "Bench Bulgarian Split Stretch": "Sehpada Bulgar Kalça Esneme",
  "Bench Calf Stretch": "Sehpada Baldır Esneme",
  "Bench Chest Stretch": "Sehpada Göğüs Esneme",
  "Bench Child's Pose": "Sehpada Çocuk Pozu",
  "Bench Couch Stretch": "Sehpada Ön Bacak (Couch) Esneme",
  "Bench Dips": "Sehpada Dips (Bench Dips)",
  "Bench Figure-4 Glute Stretch": "Sehpada 4 Figürü Kalça Esneme",
  "Bench Hamstring Stretch": "Sehpada Arka Bacak Esneme",
  "Bench Lat Stretch": "Sehpada Kanat Esneme",
  "Bench Leg Pull-In": "Sehpada Diz Çekme",
  "Barbell Bench Press": "Halter Bench Press",
  "Bench Pull": "Sehpada Yüzüstü Halter Kürek Çekiş",
  "Bent Arm Barbell Pullover": "Bükük Kol Halter Pullover",
  "Bent-Arm EZ-Bar Pullover": "Bükük Kol EZ Bar Pullover",
  "Bent-Over Dumbbell Row": "Dambılla Öne Eğilerek Kürek Çekiş",
  "Bent-Over EZ-Bar Row": "EZ Barla Öne Eğilerek Kürek Çekiş",
  "Dumbbell Bicep Curl": "Dambıl Biceps Curl",
  "Bicycle Crunch": "Bisiklet Crunch",
  "Bird-Dog": "Bird Dog (Kuş-Köpek)",
  "Bird Dog Hold": "Bird Dog Bekletme",
  "Boat Pose": "Kayık Pozu",
  "Bodyweight Calf Raise": "Baldır Kaldırma",
  "Bodyweight Good Morning": "Ağırlıksız Good Morning",
  "Bodyweight Lateral Raise": "Ağırlıksız Yana Kol Kaldırma",
  "Bodyweight Overhead Press": "Ağırlıksız Baş Üstü Press",
  "Bodyweight Reverse Lunge": "Geri Lunge",
  "Bodyweight Squat": "Squat (Vücut Ağırlığı)",
  "Bow Pose": "Yay Pozu",
  "Box Jump": "Kutuya Sıçrama (Box Jump)",
  "Box Squat": "Kutuya Oturarak Squat",
  "Bulgarian Split Squat": "Dambıl Bulgar Split Squat",
  "Burpees": "Burpee",
  "Butterfly Stretch": "Kelebek Esneme",
  "Cable Bent-Over Row": "Kablo Öne Eğilerek Kürek Çekiş",
  "Cable Chest Press": "Kablo Göğüs Press",
  "Cable Crunch": "Kablo Crunch",
  "Cable Curl": "Kablo Biceps Curl",
  "Cable External Rotation": "Kablo Omuz Dış Rotasyon",
  "Cable Fly": "Kablo Fly (Crossover)",
  "Cable Front Raise": "Kablo Öne Kaldırma",
  "Cable Hammer Curl": "Kablo Hammer Curl",
  "Cable Glute Kickback": "Kablo Kalça Kickback",
  "Cable Lateral Raise": "Kablo Yana Kaldırma",
  "Cable Pallof Press": "Kablo Pallof Press",
  "Cable Tricep Kickback": "Kablo Triceps Kickback",
  "Cable Upright Row": "Kablo Upright Row",
  "Cable Wrist Curl": "Kablo Bilek Curl",
  "Camel Pose": "Deve Pozu",
  "Captain's Chair Knee Raise": "Dips İstasyonunda Diz Çekme",
  "Captain's Chair Leg Raise": "Dips İstasyonunda Bacak Kaldırma",
  "Cat-Cow": "Kedi-İnek",
  "Cat Stretch": "Kedi Esneme",
  "Chair Pose": "Sandalye Pozu",
  "Cheat Curl": "Halter Cheat Curl",
  "Machine Chest Press": "Makine Göğüs Press",
  "Chest-Supported Dumbbell Row": "Eğimli Sehpada Dambıl Kürek Çekiş",
  "Chest Supported Dumbbell Shrug": "Eğimli Sehpada Dambıl Shrug",
  "Chest-Supported Kettlebell Row": "Eğimli Sehpada Girya Kürek Çekiş",
  "Chest-Supported Smith Machine Row": "Smith Makinede Göğüs Destekli Kürek Çekiş",
  "Child's Pose": "Çocuk Pozu",
  "Chin Tuck Hold": "Çene Geri Çekme Bekletme",
  "Chin-Ups": "Chin-Up (Ters Tutuş Barfiks)",
  "Clamshells": "Clamshell",
  "Clamshell Hold": "Clamshell Bekletme",
  "Clap Push-Ups": "Alkışlı Şınav",
  "Clean": "Halter Clean",
  "Clean and Jerk": "Halter Clean and Jerk",
  "Close-Grip Barbell Curl": "Dar Tutuş Halter Curl",
  "Close-Grip Bench Press": "Dar Tutuş Halter Bench Press",
  "Close-Grip Dumbbell Bench Press": "Dar Tutuş Dambıl Bench Press",
  "Close-Grip EZ-Bar Bench Press": "Dar Tutuş EZ Bar Bench Press",
  "Close-Grip EZ-Bar Curl": "Dar Tutuş EZ Bar Curl",
  "Close-Grip Incline Bench Press": "Dar Tutuş Eğimli Halter Bench Press",
  "Close Grip Lat Pulldown": "Dar Tutuş Lat Pulldown",
  "Close-Grip Pull-Ups": "Dar Tutuş Barfiks",
  "Close Grip Push Ups": "Dar Şınav",
  "Close-Stance Leg Press": "Dar Duruş Leg Press",
  "Cobra Stretch": "Kobra Esneme",
  "Cocoons": "Koza Crunch",
  "Concentration Curl": "Dambıl Konsantrasyon Curl",
  "Cossack Squat": "Kazak Squat",
  "Cow Face Pose": "İnek Yüzü Pozu",
  "Crab Dips": "Yengeç Dips",
  "Crescent Lunge": "Hilal Lunge Pozu",
  "Cross-Body Crunch": "Çapraz Crunch",
  "Cross Body Hammer Curl": "Dambıl Çapraz Hammer Curl",
  "Cross-Body Shoulder Stretch": "Çapraz Omuz Esneme",
  "Crow Pose": "Karga Pozu",
  "Crunches": "Crunch",
  "Dancer Pose": "Dansçı Pozu",
  "Dumbbell Bench Press": "Dambıl Bench Press",
  "Dumbbell Fly": "Dambıl Fly",
  "Dumbbell Kickstand Deadlift": "Dambıl Kickstand Deadlift",
  "Dumbbell Lunge": "Dambıl Lunge",
  "Dumbbell Overhead Carry": "Tek Dambıl Baş Üstü Taşıma",
  "Dumbbell Pullover": "Dambıl Pullover",
  "Dumbbell Reverse Curl": "Dambıl Ters Tutuş Curl",
  "Dumbbell Reverse Wrist Curl": "Dambıl Ters Bilek Curl",
  "Dumbbell Shrug": "Dambıl Shrug",
  "Dumbbell Skull Crusher": "Dambıl Skull Crusher",
  "Dumbbell Somersault Squat": "Dambıl Somersault Squat",
  "Dumbbell Squat": "Dambıl Squat",
  "Dumbbell Sumo Squat": "Dambıl Sumo Squat",
  "Dumbbell Svend Press": "Dambıl Svend Press",
  "Dead Bug": "Dead Bug (Ölü Böcek)",
  "Dead Bug Hold": "Dead Bug Bekletme",
  "Dead Hang": "Barda Asılı Durma",
  "Barbell Deadlift": "Halter Deadlift",
  "Decline Bench Press": "Dambıl Decline Bench Press",
  "Decline Barbell Bench Press": "Halter Decline Bench Press",
  "Decline EZ-Bar Bench Press": "EZ Bar Decline Bench Press",
  "Decline Crunch": "Decline Sehpada Crunch",
  "Decline Dumbbell Fly": "Dambıl Decline Fly",
  "Decline Push-Up": "Ayaklar Yüksekte Şınav",
  "Deficit Deadlift": "Halter Deficit Deadlift",
  "Deficit Push Ups": "Derin (Deficit) Şınav",
  "Diamond Push Ups": "Elmas Şınav",
  "Chest Dips": "Paralel Barda Dips",
  "Dolphin Pose": "Yunus Pozu",
  "Donkey Calf Raise": "Eğilerek Baldır Kaldırma",
  "Doorway Chest Stretch": "Kapı Aralığında Göğüs Esneme",
  "Double Dumbbell Kickstand Deadlift": "Çift Dambıl Kickstand Deadlift",
  "Double Dumbbell Overhead Carry": "Çift Dambıl Baş Üstü Taşıma",
  "Double Kettlebell Bicep Curl": "Çift Girya Biceps Curl",
  "Double Kettlebell Clean": "Çift Girya Clean",
  "Double Kettlebell Clean and Press": "Çift Girya Clean and Press",
  "Double Kettlebell Dead Clean": "Çift Girya Dead Clean",
  "Double Kettlebell Dead Split Snatch": "Çift Girya Split Snatch",
  "Double Kettlebell Jerk": "Çift Girya Jerk",
  "Double Kettlebell Overhead Carry": "Çift Girya Baş Üstü Taşıma",
  "Double Kettlebell Overhead Press": "Çift Girya Omuz Press",
  "Double Kettlebell Push Press": "Çift Girya Push Press",
  "Double Kettlebell Rear Delt Row": "Çift Girya Arka Omuz Kürek Çekiş",
  "Double Kettlebell Row": "Çift Girya Kürek Çekiş",
  "Double Kettlebell Split Jerk": "Çift Girya Split Jerk",
  "Double Kettlebell Swing Snatch": "Çift Girya Swing Snatch",
  "Downward-Facing Dog": "Aşağı Bakan Köpek",
  "Downward Dog Knee Tuck": "Aşağı Bakan Köpekten Diz Çekme",
  "Downward Dog Pedal": "Aşağı Bakan Köpek Pedal",
  "Downward Dog to Knee Drive": "Aşağı Bakan Köpekten Diz Sürme",
  "Downward Dog to Low Lunge": "Aşağı Bakan Köpekten Alçak Lunge",
  "Downward Dog to Plank": "Aşağı Bakan Köpekten Plank",
  "Downward Dog to Upward Dog": "Aşağı Köpekten Yukarı Köpeğe",
  "Drag Curl": "Halter Drag Curl",
  "Dragon Flag": "Dragon Flag",
  "Dumbbell Bench Pull": "Sehpada Yüzüstü Dambıl Kürek Çekiş",
  "Dumbbell Calf Raise": "Dambılla Baldır Kaldırma",
  "Dumbbell Deadlift": "Dambıl Deadlift",
  "Dumbbell Face Pull": "Dambıl Face Pull",
  "Dumbbell Farmer's Walk": "Dambıl Farmer Walk",
  "Dumbbell Floor Press": "Dambıl Floor Press",
  "Dumbbell Front Raise": "Dambılla Öne Kaldırma",
  "Dumbbell Front Squat": "Dambıl Front Squat",
  "Dumbbell Hip Thrust": "Dambıl Hip Thrust",
  "Dumbbell Pistol Squat": "Dambıl Pistol Squat",
  "Dumbbell Push Press": "Dambıl Push Press",
  "Dumbbell Reverse Fly": "Dambıl Reverse Fly",
  "Dumbbell Romanian Deadlift": "Dambıl Romanian Deadlift",
  "Dumbbell Shoulder Press": "Dambıl Omuz Press",
  "Dumbbell Side Bend": "Dambılla Yana Eğilme",
  "Dumbbell Snatch": "Dambıl Snatch",
  "Dumbbell Split Squat": "Dambıl Split Squat",
  "Dumbbell Tricep Extension": "Dambıl Baş Üstü Triceps Extension",
  "Dumbbell Upright Row": "Dambıl Upright Row",
  "Dumbbell Windmill": "Dambıl Windmill",
  "Dumbbell Wrist Curl": "Dambıl Bilek Curl",
  "Eagle Pose": "Kartal Pozu",
  "Easy Pose": "Bağdaş Pozu",
  "Elliptical Trainer": "Eliptik Bisiklet",
  "Extended Side Angle Pose": "Uzatılmış Yan Açı Pozu",
  "EZ-Bar Bench Press": "EZ Bar Bench Press",
  "EZ-Bar Curl": "EZ Bar Curl",
  "EZ-Bar Front Raise": "EZ Barla Öne Kaldırma",
  "EZ-Bar Lying Triceps Extension": "EZ Bar Yatarak Triceps Extension",
  "EZ-Bar Overhead Tricep Extension": "EZ Bar Baş Üstü Triceps Extension",
  "EZ Bar Pullover": "EZ Bar Pullover",
  "EZ-Bar Reverse Curl": "EZ Bar Ters Tutuş Curl",
  "EZ Bar Reverse Grip Row": "EZ Bar Ters Tutuş Kürek Çekiş",
  "EZ-Bar Romanian Deadlift": "EZ Bar Romanian Deadlift",
  "EZ-Bar Shrug": "EZ Bar Shrug",
  "EZ Bar Spider Curl": "EZ Bar Spider Curl",
  "EZ-Bar Upright Row": "EZ Bar Upright Row",
  "EZ-Bar Wrist Curl": "EZ Bar Bilek Curl",
  "Cable Face Pull": "Kablo Face Pull",
  "Fish Pose": "Balık Pozu",
  "Floor EZ-Bar Press": "EZ Bar Floor Press",
  "Floor Kettlebell Pullover": "Yerde Girya Pullover",
  "Floor Press": "Halter Floor Press",
  "Flutter Kicks": "Flutter Kick (Çırpma)",
  "Front Lever": "Front Lever (Barda)",
  "Front Squat": "Halter Front Squat",
  "Garland Pose": "Çelenk Pozu (Derin Squat)",
  "Glute Bridge": "Kalça Köprüsü",
  "Glute Bridge Hold": "Kalça Köprüsü Bekletme",
  "Glute Kickback": "Dört Ayak Kalça Kickback",
  "Glute Kickback Hold": "Dört Ayak Kalça Kickback Bekletme",
  "Goblet Squat": "Goblet Squat",
  "Good Morning": "Halter Good Morning",
  "Hack Squat": "Hack Squat Makinesi",
  "Hack Squat Calf Raise": "Hack Squat Makinesinde Baldır Kaldırma",
  "Half-Kneeling Hip Flexor Rock": "Yarım Diz Kalça Önü Sallanma",
  "Half Moon Pose": "Yarım Ay Pozu",
  "Dumbbell Hammer Curl": "Dambıl Hammer Curl",
  "Handstand Push Ups": "Amuda Kalkarak Şınav",
  "Hang Clean": "Halter Hang Clean",
  "Hang Power Clean": "Halter Hang Power Clean",
  "Hanging Knee Raise": "Barda Asılı Diz Çekme",
  "Hanging Leg Raise": "Barda Asılı Bacak Kaldırma",
  "Hanging Pike": "Barda Asılı Pike",
  "Happy Baby Pose": "Mutlu Bebek Pozu",
  "Head-to-Knee Pose": "Baş Dize Pozu",
  "Heel-Elevated Squat": "Topuk Yükseltilmiş Halter Squat",
  "Heel-to-Toe Walk": "Topuk-Burun Yürüyüşü",
  "Hero Pose": "Kahraman Pozu",
  "Hex Bar Deadlift": "Trap Bar Deadlift",
  "High-Foot Leg Press": "Yüksek Ayak Leg Press",
  "High Knees": "Yüksek Diz Koşusu",
  "High Plank": "Düz Kol Plank",
  "Machine Hip Abduction": "Makine Kalça Açma (Abductor)",
  "Hip Adduction": "Makine Kalça Kapama (Adductor)",
  "Barbell Hip Thrust": "Halter Hip Thrust",
  "Hollow Body Hold": "Hollow Body Bekletme",
  "Horizontal Leg Press": "Yatay Leg Press",
  "Human Flag": "İnsan Bayrağı",
  "Incline EZ-Bar Bench Press": "EZ Bar Eğimli Bench Press",
  "Incline Barbell Bench Press": "Halter Eğimli Bench Press",
  "Incline Dumbbell Curl": "Eğimli Sehpada Dambıl Curl",
  "Incline Dumbbell Press": "Dambıl Eğimli Bench Press",
  "Incline Dumbbell Fly": "Dambıl Eğimli Fly",
  "Incline Hammer Curl": "Eğimli Sehpada Hammer Curl",
  "Incline Push-Up": "Eğimli Şınav (Eller Yüksekte)",
  "Incline Treadmill Walk": "Eğimli Koşu Bandı Yürüyüşü",
  "Inverted Row": "Halterle Ters Kürek Çekiş (Inverted Row)",
  "Isometric Neck Lateral Flexion": "İzometrik Boyun Yan Direnç",
  "Jackknife Sit-Up": "Çakı Mekik",
  "Jefferson Curl": "Jefferson Curl",
  "Jump Rope": "İp Atlama",
  "Jump Squat": "Sıçramalı Squat",
  "Jumping Jacks": "Jumping Jack",
  "Kettlebell Bulgarian Split Squat": "Girya Bulgar Split Squat",
  "Kettlebell Close-Grip Floor Press": "Girya Dar Tutuş Floor Press",
  "Kettlebell Concentration Curl": "Girya Konsantrasyon Curl",
  "Kettlebell Deadlift": "Girya Deadlift",
  "Kettlebell Farmer's Walk": "Girya Farmer Walk",
  "Kettlebell Floor Press": "Girya Floor Press",
  "Kettlebell Goblet Lunge": "Girya Goblet Lunge",
  "Kettlebell Halo": "Girya Halo",
  "Kettlebell Hammer Curl": "Girya Hammer Curl",
  "Kettlebell Hip Thrust": "Girya Hip Thrust",
  "Kettlebell Kickstand Deadlift": "Girya Kickstand Deadlift",
  "Kettlebell Lunge Press": "Girya Lunge ve Press",
  "Kettlebell Offset Reverse Lunge and Press": "Girya Tek Taraflı Geri Lunge ve Press",
  "Kettlebell Overhead Carry": "Girya Baş Üstü Taşıma",
  "Kettlebell Overhead Tricep Extension": "Girya Baş Üstü Triceps Extension",
  "Kettlebell Pistol Squat": "Girya Pistol Squat",
  "Kettlebell Pullover": "Girya Pullover",
  "Kettlebell Reverse Lunge": "Girya Geri Lunge",
  "Kettlebell Reverse Wrist Curl": "Girya Ters Bilek Curl",
  "Kettlebell Rotational Lunge": "Girya Dönüşlü Lunge",
  "Kettlebell Russian Twist": "Girya Russian Twist",
  "Kettlebell Shrug": "Girya Shrug",
  "Kettlebell Single Leg Deadlift": "Girya Tek Bacak Deadlift",
  "Kettlebell Skull Crusher": "Girya Skull Crusher",
  "Kettlebell Squat": "Girya Squat",
  "Kettlebell Sumo Deadlift": "Girya Sumo Deadlift",
  "Kettlebell Sumo High Pull": "Girya Sumo High Pull",
  "Kettlebell Svend Press": "Girya Svend Press",
  "Kettlebell Swing": "Girya Swing",
  "Kettlebell Swing Clean": "Girya Swing Clean",
  "Kettlebell Turkish Get Ups": "Girya Turkish Get-Up",
  "Kettlebell Windmills": "Girya Windmill",
  "Kettlebell Wrist Curl": "Girya Bilek Curl",
  "Knee Push Ups": "Dizüstü Şınav",
  "Knee-to-Chest Stretch": "Dizi Göğse Çekme Esnemesi",
  "Kneeling Cable Row": "Diz Üstü Kablo Kürek Çekiş",
  "Kneeling Hip Flexor Stretch": "Diz Üstü Kalça Önü Esneme",
  "Kneeling Wrist Stretch": "Diz Üstü Bilek Esneme",
  "L Sit": "L-Sit",
  "Landmine Press": "Landmine Press",
  "Lat Pulldown": "Lat Pulldown",
  "Dumbbell Lateral Raise": "Dambıl Yana Kaldırma (Lateral Raise)",
  "Lying Leg Curl": "Yatarak Leg Curl (Makine)",
  "Leg Extension": "Leg Extension (Makine)",
  "Leg Press": "Leg Press",
  "Legs-Up-the-Wall Pose": "Bacaklar Duvarda Pozu",
  "Lizard Stretch": "Kertenkele Esneme",
  "Locust Pose": "Çekirge Pozu",
  "Low Lunge": "Alçak Lunge Pozu",
  "Low Lunge to Half Split": "Alçak Lunge'dan Yarım Split",
  "Lunge": "Lunge",
  "Lying Leg Raise": "Yatarak Bacak Kaldırma",
  "Lying Tricep Extension": "Dambıl Yatarak Triceps Extension",
  "Machine Back Extension": "Makine Bel Extension",
  "Machine Bicep Curl": "Makine Biceps Curl",
  "Machine Calf Raise": "Makine Baldır Kaldırma",
  "Machine Chest Fly": "Makine Göğüs Fly",
  "Machine Preacher Curl": "Makine Preacher Curl",
  "Machine Seated Crunch": "Makine Crunch",
  "Machine Shoulder Press": "Makine Omuz Press",
  "Machine Triceps Extension": "Makine Triceps Extension",
  "Medicine Ball Slam": "Sağlık Topu Slam",
  "Mountain Climbers": "Mountain Climber (Dağ Tırmanışı)",
  "Mountain Pose": "Dağ Pozu",
  "Muscle Snatch": "Halter Muscle Snatch",
  "Muscle Ups": "Muscle-Up",
  "Neck Side Stretch": "Boyun Yan Esneme",
  "Negative Pull Ups": "Negatif Barfiks",
  "Neutral Grip Pull Ups": "Nötr Tutuş Barfiks",
  "Nordic Hamstring Curl": "Nordic Hamstring Curl",
  "Barbell Overhead Press": "Halter Overhead Press",
  "One-Arm Dumbbell Push Press": "Tek Kol Dambıl Push Press",
  "One-Arm Dumbbell Swing": "Tek Kol Dambıl Swing",
  "One Arm Kettlebell Bicep Curl": "Tek Kol Girya Biceps Curl",
  "One-Arm Kettlebell Bottoms-Up Press": "Tek Kol Girya Bottoms-Up Press",
  "One Arm Kettlebell Floor Glute Bridge Press": "Tek Kol Girya Köprüde Floor Press",
  "One Arm Kettlebell Floor Press": "Tek Kol Girya Floor Press",
  "One Arm Kettlebell Front Squat": "Tek Kol Girya Front Squat",
  "One Arm Kettlebell Push Press": "Tek Kol Girya Push Press",
  "One Arm Kettlebell Row": "Tek Kol Girya Kürek Çekiş",
  "One Arm Kettlebell Shoulder Press": "Tek Kol Girya Omuz Press",
  "One Arm Kettlebell Swing": "Tek Kol Girya Swing",
  "One-Arm Kettlebell Tricep Kickback": "Tek Kol Girya Triceps Kickback",
  "One-Arm Landmine Press": "Tek Kol Landmine Press",
  "One-Arm Lat Pulldown": "Tek Kol Kablo Lat Pulldown",
  "One-Arm Single-Leg Dumbbell Romanian Deadlift": "Tek Kol Tek Bacak Dambıl Romanian Deadlift",
  "One-Arm Single-Leg Kettlebell Romanian Deadlift": "Tek Kol Tek Bacak Girya Romanian Deadlift",
  "Overhead Squat": "Halter Overhead Squat",
  "Overhead Tricep Extension": "Tek Dambıl Baş Üstü Triceps Extension",
  "Overhead Triceps Stretch": "Baş Üstü Arka Kol Esneme",
  "Pause Deadlift": "Duraklamalı Halter Deadlift",
  "Pause Pull-Up": "Duraklamalı Barfiks",
  "Pause Squat": "Duraklamalı Halter Squat",
  "Paused Bench Press": "Duraklamalı Halter Bench Press",
  "Paused Incline Bench Press": "Duraklamalı Eğimli Halter Bench Press",
  "Paused Overhead Press": "Duraklamalı Halter Overhead Press",
  "Pec Deck": "Pec Deck (Makine Fly)",
  "Pendlay Row": "Halter Pendlay Row",
  "Pigeon Stretch": "Güvercin Esneme",
  "Pike Push Ups": "Pike Şınav",
  "Pilates Kneeling Side Kick": "Pilates Diz Üstü Yan Tekme",
  "Pilates Leg Pull Back": "Pilates Ters Plankta Bacak Kaldırma",
  "Pilates Leg Pull Front": "Pilates Plankta Bacak Kaldırma",
  "Pilates Roll Down": "Pilates Roll Down",
  "Pilates Roll Over": "Pilates Roll Over",
  "Pilates Saw": "Pilates Testere",
  "Pilates Side Bend": "Pilates Yan Köprü",
  "Pilates Spine Stretch Forward": "Pilates Öne Omurga Esnemesi",
  "Pilates Spine Twist": "Pilates Omurga Dönüşü",
  "Pistol Squat": "Pistol Squat (Tek Bacak)",
  "Planche": "Planche",
  "Plank": "Plank",
  "Plate-Loaded Donkey Calf Raise": "Makinede Eğilerek Baldır Kaldırma",
  "Plate-Loaded Glute Drive": "Hip Thrust Makinesi",
  "Plate-Loaded Lateral Raise": "Makine Yana Kaldırma",
  "Plate-Loaded Shrug": "Makine Shrug",
  "Plate Pinch": "Plaka Sıkıştırarak Taşıma",
  "Plate Pullover": "Plaka Pullover",
  "Plow Pose": "Saban Pozu",
  "Plyo Lunge": "Sıçramalı Lunge",
  "Plyo Push-Up": "Patlayıcı Şınav",
  "Preacher Curl": "EZ Bar Preacher Curl",
  "Preacher Hammer Curl": "Dambıl Preacher Hammer Curl",
  "Pseudo Planche Push Ups": "Pseudo Planche Şınav",
  "Pull-Up": "Barfiks",
  "Puppy Pose": "Yavru Köpek Pozu",
  "Push Jerk": "Halter Push Jerk",
  "Push Press": "Halter Push Press",
  "Push-Up": "Şınav",
  "Pyramid Pose": "Piramit Pozu",
  "Rack Pull": "Halter Rack Pull",
  "Rear Delt Fly": "Dambıl Arka Omuz Fly",
  "Reverse Crunches": "Ters Crunch",
  "Reverse Curl": "Halter Ters Tutuş Curl",
  "Reverse Grip Bent Over Row": "Halterle Ters Tutuş Kürek Çekiş",
  "Reverse Grip Lat Pulldown": "Ters Tutuş Lat Pulldown",
  "Reverse Lunge": "Dambıl Geri Lunge",
  "Reverse Nordic Curl": "Ters Nordic Curl",
  "Reverse Plank": "Ters Plank",
  "Reverse Plank Dips": "Ters Plank Dips",
  "Reverse Tabletop Hip Pulses": "Ters Masa Kalça Pulse",
  "Reverse Tabletop Hold": "Ters Masa Bekletme",
  "Revolved Chair Pose": "Dönüşlü Sandalye Pozu",
  "Revolved Crescent Lunge": "Dönüşlü Hilal Lunge Pozu",
  "Ring Dead Hang": "Halkada Asılı Durma",
  "Ring Dips": "Halkada Dips",
  "Ring Face Pull": "Halkada Face Pull",
  "Ring Muscle-Up": "Halkada Muscle-Up",
  "Ring Push-Up": "Halkada Şınav",
  "Ring Row": "Halkada Kürek Çekiş",
  "Rings Inverted Row": "Halkada Ters Kürek Çekiş",
  "Romanian Deadlift": "Halter Romanian Deadlift",
  "Rope Climb": "Halat Tırmanma",
  "Rowing Machine": "Kürek Makinesi",
  "Running": "Koşu",
  "Russian Twist": "Russian Twist",
  "Corpse Pose": "Ceset Pozu (Savasana)",
  "Scapular Pull Ups": "Skapular Barfiks",
  "Scissor Kicks": "Makas Tekme",
  "Seated Barbell Overhead Press": "Oturarak Halter Omuz Press",
  "Seated Cable Row": "Oturarak Kablo Kürek Çekiş",
  "Seated Calf Raise": "Oturarak Baldır Makinesi",
  "Seated Dumbbell Shoulder Press": "Oturarak Dambıl Omuz Press",
  "Seated Dumbbell Curl": "Oturarak Dambıl Curl",
  "Seated Dumbbell Lateral Raise": "Oturarak Dambıl Yana Kaldırma",
  "Seated Dumbbell Tricep Extension": "Oturarak Dambıl Baş Üstü Triceps Extension",
  "Seated Forward Fold": "Oturarak Öne Eğilme",
  "Seated Leg Curl": "Oturarak Leg Curl (Makine)",
  "Seated Smith Machine Shoulder Press": "Smith Makinede Oturarak Omuz Press",
  "Seated Spinal Twist": "Oturarak Omurga Dönüşü",
  "Seated Straddle Stretch": "Oturarak Bacaklar Açık Esneme",
  "Barbell Shrug": "Halter Shrug",
  "Side Lunge": "Yan Lunge",
  "Side-Lying Hip Abduction": "Yan Yatarak Bacak Açma",
  "Side-Lying Hip Abduction Hold": "Yan Yatarak Bacak Açma Bekletme",
  "Side Lying Hip Adduction": "Yan Yatarak İç Bacak Kaldırma",
  "Side-Lying Hip Adduction Hold": "Yan Yatarak İç Bacak Bekletme",
  "Side-Lying Lateral Raise": "Yan Yatarak Dambıl Yana Kaldırma",
  "Side Plank": "Yan Plank",
  "Side Plank with Leg Lift": "Yan Plankta Bacak Kaldırma",
  "Side Plank Leg Lift Hold": "Yan Plankta Bacak Kaldırma Bekletme",
  "Single-Arm Chest-Supported Dumbbell Row": "Eğimli Sehpada Tek Kol Dambıl Kürek Çekiş",
  "Single-Arm Dumbbell Row": "Tek Kol Dambıl Kürek Çekiş",
  "Single-Arm Dumbbell Overhead Tricep Extension": "Tek Kol Dambıl Baş Üstü Triceps Extension",
  "Single-Arm Hammer Curl": "Tek Kol Dambıl Hammer Curl",
  "Single-Arm Machine Shoulder Press": "Tek Kol Makine Omuz Press",
  "Single-Arm Plate-Loaded Lateral Raise": "Tek Kol Makine Yana Kaldırma",
  "Single Arm Tricep Pushdown": "Tek Kol Kablo Triceps Pushdown",
  "Single Dumbbell Svend Press": "Tek Dambıl Svend Press",
  "Single Leg Calf Raise": "Tek Bacak Baldır Kaldırma",
  "Single Leg Extension": "Tek Bacak Leg Extension (Makine)",
  "Single Leg Glute Bridge": "Tek Bacak Kalça Köprüsü",
  "Single-Leg Glute Bridge Hold": "Tek Bacak Kalça Köprüsü Bekletme",
  "Single Leg Lying Leg Curl": "Tek Bacak Yatarak Leg Curl (Makine)",
  "Single Leg Press": "Tek Bacak Leg Press",
  "Single Leg Romanian Deadlift": "Dambıl Tek Bacak Romanian Deadlift",
  "Sit-Ups": "Mekik",
  "Skull Crusher": "EZ Bar Skull Crusher",
  "Sled Row": "Kızak Kürek Çekiş",
  "Smith Machine Bench Press": "Smith Makinede Bench Press",
  "Smith Machine Bent Over Row": "Smith Makinede Öne Eğilerek Kürek Çekiş",
  "Smith Machine Bulgarian Split Squat": "Smith Makinede Bulgar Split Squat",
  "Smith Machine Calf Raise": "Smith Makinede Baldır Kaldırma",
  "Smith Machine Decline Bench Press": "Smith Makinede Decline Bench Press",
  "Smith Machine Front Squat": "Smith Makinede Front Squat",
  "Smith Machine Good Morning": "Smith Makinede Good Morning",
  "Smith Machine Hip Thrust": "Smith Makinede Hip Thrust",
  "Smith Machine Incline Bench Press": "Smith Makinede Eğimli Bench Press",
  "Smith Machine Romanian Deadlift": "Smith Makinede Romanian Deadlift",
  "Smith Machine Reverse Grip Bent Over Row": "Smith Makinede Ters Tutuş Kürek Çekiş",
  "Smith Machine Reverse Lunge": "Smith Makinede Geri Lunge",
  "Smith Machine Shoulder Press": "Smith Makinede Omuz Press",
  "Smith Machine Shrug": "Smith Makinede Shrug",
  "Smith Machine Split Squat": "Smith Makinede Split Squat",
  "Smith Machine Squat": "Smith Makinede Squat",
  "Smith Machine Upright Row": "Smith Makinede Upright Row",
  "Snatch": "Halter Snatch",
  "Sphinx Pose": "Sfenks Pozu",
  "Spider Curl": "Dambıl Spider Curl",
  "Split Jerk": "Halter Split Jerk",
  "Split Squat": "Split Squat",
  "Spoto Press": "Halter Spoto Press",
  "Barbell Back Squat": "Halter Squat",
  "Stability Ball Hip Bridge": "Pilates Topunda Kalça Köprüsü",
  "Stability Ball Knee Tuck": "Pilates Topuyla Diz Çekme",
  "Stability Ball Push-Up": "Pilates Topunda Ayaklar Yüksekte Şınav",
  "Stability Ball Push-Up (Hands on Ball)": "Pilates Topunda Eller Üstte Şınav",
  "Stability Ball Wall Squat": "Pilates Topuyla Duvar Squat",
  "Stair Climber": "Merdiven Makinesi",
  "Standing Calf Raise": "Ayakta Baldır Makinesi",
  "Standing Calf Stretch": "Ayakta Baldır Esneme",
  "Standing Forward Fold": "Ayakta Öne Eğilme",
  "Standing Forward Fold to Half Lift": "Ayakta Öne Eğilip Yarım Kalkma",
  "Standing Quad Stretch": "Ayakta Ön Bacak Esneme",
  "Standing Side Bend": "Ayakta Yana Eğilme",
  "Standing Side Bend Flow": "Ayakta Yana Eğilme Akışı",
  "Standing Split": "Ayakta Split Pozu",
  "Stationary Bike": "Sabit Bisiklet",
  "Step Ups": "Basamağa Çıkma (Step-Up)",
  "Stiff Leg Deadlift": "Halter Stiff Leg Deadlift",
  "Straight-Arm Pulldown": "Kablo Düz Kol Pulldown",
  "Straight-Bar Cable Front Raise": "Kablo Düz Barla Öne Kaldırma",
  "Straight Bar Dips": "Düz Barda Dips",
  "Strict Curl": "Dambıl Strict Curl",
  "Suitcase Carry": "Tek Taraflı Taşıma (Suitcase Carry)",
  "Sumo Deadlift": "Halter Sumo Deadlift",
  "Sumo Squat": "Halter Sumo Squat",
  "Superman": "Superman",
  "Supine Spinal Twist": "Sırtüstü Omurga Dönüşü",
  "Supine Windshield Wipers": "Sırtüstü Silecek",
  "Supported Shoulderstand": "Destekli Mum Duruşu",
  "Svend Press": "Plaka Svend Press",
  "T-Bar Row": "T-Bar Row",
  "Thoracic Bridge": "Torasik Köprü",
  "Thread the Needle": "İğneye İplik Geçirme Esnemesi",
  "Thread the Needle Flow": "İğneye İplik Geçirme Akışı",
  "Three-Legged Downward Dog": "Üç Bacaklı Köpek Pozu",
  "Thruster": "Halter Thruster",
  "Toes to Bar": "Toes to Bar (Barda Ayak Değdirme)",
  "Treadmill Running": "Koşu Bandında Koşu",
  "Tree Pose": "Ağaç Pozu",
  "Triangle Pose": "Üçgen Pozu",
  "Dumbbell Tricep Kickback": "Dambıl Triceps Kickback",
  "Cable Tricep Pushdown": "Kablo Triceps Pushdown",
  "TRX Bicep Curl": "TRX Biceps Curl",
  "TRX Chest Press": "TRX Göğüs Press",
  "TRX Face Pull": "TRX Face Pull",
  "TRX Hamstring Curl": "TRX Hamstring Curl",
  "TRX Lunge": "TRX Lunge",
  "TRX Pistol Squat": "TRX Pistol Squat",
  "TRX Plank": "TRX Plank",
  "TRX Row": "TRX Kürek Çekiş",
  "TRX Side Plank": "TRX Yan Plank",
  "TRX Squat": "TRX Squat",
  "TRX Triceps Extension": "TRX Triceps Extension",
  "TRX Y-Fly": "TRX Y Fly",
  "Barbell Upright Row": "Halter Upright Row",
  "Upward-Facing Dog": "Yukarı Bakan Köpek",
  "V-Bar Lat Pulldown": "V Tutamakla Lat Pulldown",
  "V-Bar Tricep Pushdown": "V Tutamakla Kablo Triceps Pushdown",
  "V-Sit": "V-Sit Bekletme",
  "V Ups": "V-Up",
  "Walking": "Yürüyüş",
  "Walking Lunge": "Yürüyerek Lunge",
  "Wall Push Ups": "Duvarda Şınav",
  "Wall Sit": "Duvarda Oturma (Wall Sit)",
  "Warrior I": "Savaşçı I Pozu",
  "Warrior III": "Savaşçı III Pozu",
  "Warrior II": "Savaşçı II Pozu",
  "Weighted Dips": "Ağırlıklı Dips",
  "Weighted Pull-Up": "Ağırlıklı Barfiks",
  "Weighted Wall Crunch": "Ağırlıklı Crunch",
  "Wide-Grip Bench Press": "Geniş Tutuş Halter Bench Press",
  "Wide Grip Pull Ups": "Geniş Tutuş Barfiks",
  "Wide Grip Push Ups": "Geniş Şınav",
  "Wide Grip Seated Cable Row": "Geniş Tutuş Oturarak Kablo Kürek Çekiş",
  "Wide-Legged Forward Fold": "Bacaklar Açık Öne Eğilme",
  "Wide-Stance Leg Press": "Geniş Duruş Leg Press",
  "Bilateral Dumbbell Wrist Curl": "Çift Dambıl Bilek Curl",
  "Wrist Roller": "Bilek Makarası (Wrist Roller)",
  "Zottman Curl": "Dambıl Zottman Curl",
};
