// Barre — 8 hareket. Barre (bar) elin bulunduğu yere otomatik yerleştirilir; sandalye/duvar da olur.
const FLOOR = 430;
const AT = (o) => ({ anchor: [210, FLOOR], torso: 90, head: 90, armN: [345, 350], legN: [270, 270, 0], ...o });
const BAR = [{ type: "barre", at: "hand" }];

export const barre = [
  {
    id: "wl-barre-plie", name: "Barre Plié", nameTr: "Barre Plié", modality: ["barre"], sub: ["beginner", "lower_body", "full_body"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "upper_legs", primary: ["quadriceps", "gluteus_maximus"], secondary: ["adductors", "hamstrings"], force: "dynamic", mechanic: "compound", met: 3.3,
    goals: ["general_fitness", "muscle_gain", "endurance"], focus: ["legs"], mat: false, props: BAR,
    frames: [AT({}), AT({ legN: [318, 258, 0], torso: 90 })],
    desc: "Bend the knees over the toes while the torso stays tall, resting a hand on a barre, counter or chair for balance.",
    tips: ["Keep your tailbone pointing straight down.", "Press the floor evenly through the whole foot."],
    instructions: ["Stand tall beside a barre, counter or chair back with your heels together and toes turned slightly out.", "Inhale and bend your knees over your toes, keeping your torso upright.", "Lower only as far as your heels can stay down.", "Exhale and press up through the floor. Repeat 12 to 16 times."],
    instructionsTr: ["Bir barın, tezgahın ya da sandalye arkalığının yanında dik dur; topuklar bitişik, parmak uçları hafif dışarıda olsun.", "Nefes al ve gövdeni dik tutarak dizlerini parmaklarının üzerine bük.", "Topukların yerde kalabildiği kadar in.", "Nefes ver ve yeri iterek yüksel. 12–16 tekrar yap."],
    tipsTr: ["Kuyruk sokumunu düz aşağı baktır.", "Ayağının tamamıyla yeri eşit it."],
    descTr: "Dik bir gövdeyle dizleri parmakların üzerine bükmek; denge için bir el barda, tezgahta ya da sandalyede durur.",
  },
  {
    id: "wl-barre-releve", name: "Barre Relevé", nameTr: "Barre Relevé", modality: ["barre"], sub: ["beginner", "balance_posture"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "lower_legs", primary: ["gastrocnemius", "soleus"], secondary: ["quadriceps"], force: "dynamic", mechanic: "isolation", met: 3,
    goals: ["general_fitness", "endurance"], focus: ["calves"], mat: false, props: BAR,
    frames: [AT({}), AT({ anchor: [210, FLOOR - 30], legN: [270, 270, 305], torso: 90 })],
    desc: "Rise onto the balls of the feet with a tall spine and lower slowly; builds calf strength and ankle stability.",
    tips: ["Rise straight up; do not roll the ankles out.", "Lower slower than you lift."],
    instructions: ["Stand tall with your feet together and a hand on a barre or chair.", "Exhale and rise onto the balls of your feet, lifting your heels as high as you can.", "Hold for a breath, then lower slowly.", "Repeat 15 to 20 times."],
    instructionsTr: ["Ayaklar bitişik, bir elin barda ya da sandalyede dik dur.", "Nefes ver ve topuklarını olabildiğince kaldırarak ayak ucuna yüksel.", "Bir nefes bekle, sonra yavaşça in.", "15–20 tekrar yap."],
    tipsTr: ["Dümdüz yüksel; ayak bileklerini dışarı yuvarlama.", "İnişi kalkıştan yavaş yap."],
    descTr: "Omurga dikken ayak uçlarına yükselip yavaşça inmek: baldır gücünü ve ayak bileği stabilitesini geliştirir.",
  },
  {
    id: "wl-barre-chair-pulse", name: "Barre Chair Pose Pulse", nameTr: "Barre Sandalye Pozu Nabzı", modality: ["barre"], sub: ["lower_body", "full_body"], level: "intermediate", impact: "low",
    equipment: null, bodyPart: "upper_legs", primary: ["quadriceps", "gluteus_maximus"], secondary: ["hamstrings", "erector_spinae"], force: "static", mechanic: "compound", met: 4,
    goals: ["muscle_gain", "endurance", "fat_loss"], focus: ["legs"], mat: false,
    frames: [{ anchor: [210, FLOOR], torso: 72, head: 76, armN: [20, 15], legN: [322, 258, 0] }, { anchor: [210, FLOOR], torso: 66, head: 70, armN: [20, 15], legN: [334, 256, 0] }],
    desc: "Hold a low squat and pulse in tiny movements until the thighs burn; a classic barre burnout.",
    tips: ["Keep the pulses small and quick.", "Keep your weight in your heels."],
    instructions: ["Stand with your feet together and sit back into a squat with your arms forward.", "Lower an inch, then rise an inch in small, quick pulses.", "Keep your chest lifted and your weight in your heels.", "Pulse for 30 to 45 seconds, then rest."],
    instructionsTr: ["Ayaklar bitişik dur ve kollarını öne uzatıp geriye çömel.", "Bir parmak aşağı in, bir parmak yüksel: küçük ve hızlı nabızlar yap.", "Göğsünü kaldırıp ağırlığını topuklarında tut.", "30–45 saniye nabız at, sonra dinlen."],
    tipsTr: ["Nabızları küçük ve hızlı tut.", "Ağırlığını topuklarında tut."],
    descTr: "Alçak bir çömelmede kalıp küçük hareketlerle nabız atmak; klasik bir barre yorma hareketi.",
  },
  {
    id: "wl-barre-arabesque-lift", name: "Barre Arabesque Lift", nameTr: "Barre Arabesk Kaldırış", modality: ["barre"], sub: ["lower_body", "balance_posture"], level: "intermediate", impact: "low",
    equipment: null, bodyPart: "upper_legs", primary: ["gluteus_maximus", "hamstrings"], secondary: ["erector_spinae", "gluteus_medius"], force: "dynamic", mechanic: "isolation", met: 3,
    goals: ["muscle_gain", "general_fitness"], focus: ["glutes"], mat: false, props: BAR,
    frames: [AT({}), AT({ torso: 84, head: 88, legF: [214, 214, 265] })],
    desc: "Lift one straight leg behind you with a long spine to target the glutes while balancing on the other leg.",
    tips: ["Lift from the glute, not by arching the lower back.", "Keep the hips square."],
    instructions: ["Stand tall with a hand on a barre or chair and your weight on one leg.", "Extend the other leg straight behind you with a pointed toe.", "Lift it up to hip height without arching your back, then lower with control.", "Do 12 to 15 lifts, then switch legs."],
    instructionsTr: ["Bir elin barda ya da sandalyede, ağırlığın tek bacakta dik dur.", "Diğer bacağını parmak ucun uzun biçimde arkaya düz uzat.", "Belini kavislendirmeden kalça hizasına kaldır, sonra kontrolle indir.", "12–15 kaldırış yap, sonra bacak değiştir."],
    tipsTr: ["Beli kavislendirerek değil, kalçadan kaldır.", "Kalçaları öne dönük tut."],
    descTr: "Omurga uzunken tek bacağı düz biçimde arkaya kaldırmak: diğer bacak üzerinde dengelenirken kalçayı çalıştırır.",
  },
  {
    id: "wl-barre-front-leg-lift", name: "Barre Front Leg Lift", nameTr: "Barre Öne Bacak Kaldırış", modality: ["barre"], sub: ["lower_body", "core"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "upper_legs", primary: ["hip_flexors", "quadriceps"], secondary: ["rectus_abdominis"], force: "dynamic", mechanic: "isolation", met: 3,
    goals: ["general_fitness", "endurance"], focus: ["legs", "core"], mat: false, props: BAR,
    frames: [AT({ legF: [320, 320, 350] }), AT({ legF: [355, 355, 20] })],
    desc: "Lift the working leg forward with a flexed core and a tall spine, building hip flexor strength and control.",
    tips: ["Do not lean back to gain height.", "Keep the standing leg strong."],
    instructions: ["Stand tall with a hand on a barre or chair and one foot slightly forward.", "Lift the front leg straight up to a comfortable height without leaning back.", "Hold for a breath, then lower slowly.", "Do 12 to 15, then switch legs."],
    instructionsTr: ["Bir elin barda ya da sandalyede, bir ayağın hafif önde dik dur.", "Öndeki bacağı geriye yaslanmadan rahat bir yüksekliğe düz kaldır.", "Bir nefes bekle, sonra yavaşça indir.", "12–15 tekrar yap, sonra bacak değiştir."],
    tipsTr: ["Yükseklik için geriye yaslanma.", "Destek bacağını güçlü tut."],
    descTr: "Karın aktif ve omurga dikken çalışan bacağı öne kaldırmak: kalça fleksörü gücünü ve kontrolünü geliştirir.",
  },
  {
    id: "wl-barre-tendu", name: "Barre Tendu Slide", nameTr: "Barre Tendu Kayma", modality: ["barre"], sub: ["beginner", "balance_posture"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "lower_legs", primary: ["gastrocnemius", "quadriceps"], secondary: ["hip_flexors"], force: "dynamic", mechanic: "isolation", met: 2.5,
    goals: ["general_fitness", "mobility"], focus: ["legs"], mat: false, props: BAR,
    frames: [AT({}), AT({ legF: [305, 305, 290] })],
    desc: "Slide one foot along the floor into a pointed toe and back; a precise warm-up for the feet, calves and hips.",
    tips: ["Keep the hips level and the heel moving first.", "Press through the big toe as you point."],
    instructions: ["Stand tall with a hand on a barre and your feet together.", "Slide one foot forward along the floor until only the toes touch, with a long pointed foot.", "Slide back in, pulling the heel to the other foot.", "Repeat 10 to 12 times, then switch."],
    instructionsTr: ["Bir elin barda, ayakların bitişik dik dur.", "Bir ayağını yer boyunca öne kaydır; yalnızca parmak uçların değsin, ayağın uzun ve sivri olsun.", "Topuğunu diğer ayağa çekerek geri kay.", "10–12 tekrar yap, sonra taraf değiştir."],
    tipsTr: ["Kalçalarını düz tut; önce topuk hareket etsin.", "Uzatırken baş parmağını it."],
    descTr: "Bir ayağı yerde sivri parmak ucuna kaydırıp geri getirmek; ayaklar, baldırlar ve kalçalar için hassas bir ısınma.",
  },
  {
    id: "wl-barre-knee-lift-balance", name: "Barre Knee Lift Balance", nameTr: "Barre Diz Kaldırma Dengesi", modality: ["barre"], sub: ["balance_posture", "core", "beginner"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "core", primary: ["hip_flexors", "rectus_abdominis"], secondary: ["gluteus_medius", "quadriceps"], force: "static", mechanic: "compound", met: 2.8,
    goals: ["general_fitness", "mobility"], focus: ["core", "legs"], mat: false, props: BAR,
    frames: [AT({}), AT({ legF: [18, 272, 0] })],
    desc: "Lift one knee to hip height and balance, training single-leg stability and posture.",
    tips: ["Stand tall through the crown of the head.", "Keep the standing hip level."],
    instructions: ["Stand tall with a light hand on a barre or chair.", "Lift one knee to hip height with the shin hanging down.", "Hold for 3 to 5 breaths, staying tall.", "Lower and switch legs."],
    instructionsTr: ["Bir elin barda ya da sandalyede hafifçe, dik dur.", "Bir dizini kalça hizasına kaldır; kaval kemiği aşağı sarksın.", "Dik kalarak 3–5 nefes bekle.", "İn ve bacak değiştir."],
    tipsTr: ["Başının tepesinden yukarı uzan.", "Destek tarafı kalçayı düz tut."],
    descTr: "Bir dizi kalça hizasına kaldırıp dengede durmak: tek bacak stabilitesini ve duruşu geliştirir.",
  },
  {
    id: "wl-barre-plank-knee-tuck", name: "Barre Plank Knee Tuck", nameTr: "Barre Plank Diz Çekme", modality: ["barre"], sub: ["core", "full_body"], level: "intermediate", impact: "low",
    equipment: null, bodyPart: "core", primary: ["rectus_abdominis", "transverse_abdominis"], secondary: ["hip_flexors", "anterior_deltoid"], force: "dynamic", mechanic: "compound", met: 4,
    goals: ["general_fitness", "endurance", "fat_loss"], focus: ["core"],
    frames: [
      { pelvis: [270, 296], torso: 15, head: 20, armN: [270, 270], legN: [195, 195, 100] },
      { pelvis: [270, 296], torso: 15, head: 20, armN: [270, 270], legN: [195, 195, 100], legF: [335, 190, 210] },
    ],
    desc: "From a plank, draw one knee toward the chest and return without letting the hips sag or pike.",
    tips: ["Keep the hips level; do not hike them.", "Exhale as the knee comes in."],
    instructions: ["Start in a high plank with your hands under your shoulders.", "Draw one knee toward your chest while keeping your hips level.", "Return the foot to the floor and switch sides.", "Alternate for 10 to 16 tucks."],
    instructionsTr: ["Eller omuz altında, yüksek plank pozisyonunda başla.", "Kalçanı sabit tutarak bir dizini göğsüne doğru çek.", "Ayağı yere bırak ve taraf değiştir.", "10–16 çekiş boyunca sırayla devam et."],
    tipsTr: ["Kalçanı kaldırma, düz tut.", "Diz içeri gelirken nefes ver."],
    descTr: "Plank pozisyonundan bir dizi göğse çekip kalça düşmeden ya da kalkmadan geri bırakmak.",
  },
];
