// Low Impact — 6 hareket: zıplama yok, eklem dostu kardiyo ve güç.
const FLOOR = 430;
const ST = (o) => ({ anchor: [250, FLOOR], torso: 90, head: 90, armN: [270, 270], legN: [270, 270, 0], ...o });

export const lowImpact = [
  {
    id: "wl-low-march-in-place", name: "March in Place", nameTr: "Yerinde Yürüyüş", modality: ["low_impact"], sub: ["beginner", "cardio", "full_body"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "full_body", primary: ["hip_flexors", "quadriceps"], secondary: ["gastrocnemius", "rectus_abdominis"], force: "dynamic", mechanic: "compound", met: 3.5,
    goals: ["general_fitness", "endurance", "fat_loss"], focus: ["legs"], category: "cardio", mat: false,
    frames: [ST({ armN: [320, 55], armF: [255, 305], legF: [8, 275, 0] }), ST({ armN: [255, 305], armF: [320, 55], anchorLeg: "F", legN: [8, 275, 0], legF: [270, 270, 0] })],
    desc: "Lift your knees and swing your arms in a steady march: an easy, joint-friendly way to raise the heart rate.",
    tips: ["Lift the knees as high as is comfortable.", "Swing the opposite arm with each step."],
    instructions: ["Stand tall with your arms relaxed by your sides.", "March in place, lifting each knee toward hip height.", "Swing the opposite arm forward with each step.", "Continue for 45 to 60 seconds at a steady pace."],
    instructionsTr: ["Kolların gevşek, dik dur.", "Yerinde yürü; her dizi kalça hizasına doğru kaldır.", "Her adımda karşı kolunu öne salla.", "Düzenli bir tempoyla 45–60 saniye devam et."],
    tipsTr: ["Dizleri rahat edeceğin kadar yukarı kaldır.", "Her adımda karşı kolu salla."],
    descTr: "Dizleri kaldırıp kolları sallayarak düzenli bir yürüyüş: kalp atışını eklem dostu biçimde yükseltmenin kolay yolu.",
  },
  {
    id: "wl-low-knee-lift-reach", name: "Standing Knee Lift & Reach", nameTr: "Ayakta Diz Kaldır ve Uzan", modality: ["low_impact"], sub: ["cardio", "full_body", "beginner"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "full_body", primary: ["rectus_abdominis", "hip_flexors"], secondary: ["anterior_deltoid", "quadriceps"], force: "dynamic", mechanic: "compound", met: 4,
    goals: ["general_fitness", "endurance", "fat_loss"], focus: ["core", "legs"], category: "cardio", mat: false,
    frames: [ST({ armN: [90, 90] }), ST({ torso: 82, head: 88, armN: [330, 300], legF: [20, 272, 0] })],
    desc: "Reach tall, then draw the knee up as the hands pull down: a standing crunch that raises the heart rate without impact.",
    tips: ["Stay tall; do not slump forward.", "Exhale as you crunch."],
    instructions: ["Stand tall and reach both arms overhead.", "Pull your hands down toward your chest as you lift one knee toward your elbows.", "Return to standing with your arms overhead.", "Alternate sides for 30 to 45 seconds."],
    instructionsTr: ["Dik dur ve iki kolunu başının üstüne uzat.", "Bir dizini dirseklerine doğru kaldırırken ellerini göğsüne çek.", "Kollar yukarıda dik duruşa dön.", "30–45 saniye boyunca sırayla taraf değiştir."],
    tipsTr: ["Dik kal, öne çökme.", "Kıvrılırken nefes ver."],
    descTr: "Yukarı uzanıp dizi çekerken elleri aşağı indirmek: darbesiz, ayakta bir karın hareketi.",
  },
  {
    id: "wl-low-squat-to-reach", name: "Squat to Overhead Reach", nameTr: "Çömel ve Yukarı Uzan", modality: ["low_impact"], sub: ["full_body", "cardio"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "upper_legs", primary: ["quadriceps", "gluteus_maximus"], secondary: ["anterior_deltoid", "erector_spinae"], force: "dynamic", mechanic: "compound", met: 4.5,
    goals: ["general_fitness", "fat_loss", "muscle_gain"], focus: ["legs", "glutes"], category: "strength", mat: false,
    frames: [ST({ torso: 74, head: 78, armN: [18, 14], legN: [322, 258, 0] }), ST({ armN: [92, 92] })],
    desc: "Sit into a squat, then stand tall and reach overhead; a flowing, no-jump full-body move.",
    tips: ["Keep your knees tracking over your toes.", "Reach tall as you stand."],
    instructions: ["Stand with your feet hip-width apart.", "Sit back into a squat with your arms forward.", "Press up through your feet and reach both arms overhead.", "Repeat smoothly for 12 to 15 reps."],
    instructionsTr: ["Ayaklar kalça genişliğinde dur.", "Kollarını öne uzatıp geriye çömel.", "Ayaklarınla yeri iterek yüksel ve iki kolunu yukarı uzat.", "12–15 tekrarı akıcı biçimde yap."],
    tipsTr: ["Dizlerini parmaklarının doğrultusunda tut.", "Doğrulurken yukarı uzan."],
    descTr: "Çömelip doğrularak yukarı uzanmak; zıplamadan akıcı, tüm vücut bir hareket.",
  },
  {
    id: "wl-low-wall-push-up", name: "Wall Push-Up", nameTr: "Duvarda Şınav", modality: ["low_impact"], sub: ["beginner", "full_body"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "chest", primary: ["pectoralis_major"], secondary: ["triceps_brachii", "anterior_deltoid"], force: "push", mechanic: "compound", met: 3.5,
    goals: ["general_fitness", "muscle_gain", "strength"], focus: ["chest", "arms"], category: "strength", mat: false,
    frames: [
      { anchor: [160, FLOOR], torso: 76, head: 78, armN: [14, 14], legN: [258, 258, 0], props: undefined },
      { anchor: [160, FLOOR], torso: 70, head: 74, armN: [320, 20], legN: [255, 255, 0] },
    ],
    props: [{ type: "wall", at: "hand" }],
    desc: "A beginner-friendly push-up against a wall that trains the chest and arms with very little load on the joints.",
    tips: ["Keep your body in one straight line.", "Move slowly and breathe out as you press."],
    instructions: ["Stand facing a wall at arm's length, hands on the wall at shoulder height.", "Bend your elbows to bring your chest toward the wall, body straight.", "Press back to the start.", "Do 10 to 15 repetitions."],
    instructionsTr: ["Kol boyu uzaklıkta duvara bak; elleri omuz hizasında duvarda olsun.", "Vücudun düz kalırken dirseklerini bükerek göğsünü duvara yaklaştır.", "İterek başlangıca dön.", "10–15 tekrar yap."],
    tipsTr: ["Vücudunu tek düz çizgide tut.", "Yavaş git, iterken nefes ver."],
    descTr: "Duvara karşı yapılan, yeni başlayanlara uygun şınav: eklemlere çok az yük bindirerek göğüs ve kolları çalıştırır.",
  },
  {
    id: "wl-low-step-back-lunge", name: "Step-Back Lunge", nameTr: "Geri Adım Hamle", modality: ["low_impact"], sub: ["full_body", "beginner"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "upper_legs", primary: ["quadriceps", "gluteus_maximus"], secondary: ["hamstrings", "adductors"], force: "push", mechanic: "compound", met: 4,
    goals: ["general_fitness", "muscle_gain", "fat_loss"], focus: ["legs", "glutes"], category: "strength", mat: false,
    frames: [ST({}), ST({ torso: 86, head: 88, anchor: [300, FLOOR], legN: [334, 262, 0], legF: [250, 200, 205] })],
    desc: "Step one foot back and lower into a lunge, then return; easier on the knees than a jumping or walking lunge.",
    tips: ["Keep the front knee over the ankle.", "Push through the front heel to stand."],
    instructions: ["Stand tall with your feet hip-width apart.", "Step one foot back and lower until both knees are about 90 degrees.", "Press through the front heel to return to standing.", "Do 8 to 12 on each side."],
    instructionsTr: ["Ayaklar kalça genişliğinde dik dur.", "Bir ayağını geri at ve iki diz de yaklaşık 90 derece olana kadar in.", "Öndeki topukla iterek ayağa kalk.", "Her tarafta 8–12 tekrar yap."],
    tipsTr: ["Öndeki dizi ayak bileğinin üzerinde tut.", "Kalkarken öndeki topuğu it."],
    descTr: "Bir ayağı geri atıp hamleye inmek ve geri dönmek; zıplamalı ya da yürüyüşlü hamleden dizlerde daha rahattır.",
  },
  {
    id: "wl-low-bridge-march", name: "Glute Bridge March", nameTr: "Köprü Yürüyüşü", modality: ["low_impact"], sub: ["beginner", "recovery", "full_body"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "upper_legs", primary: ["gluteus_maximus", "hamstrings"], secondary: ["rectus_abdominis", "hip_flexors"], force: "dynamic", mechanic: "compound", met: 3.5,
    goals: ["general_fitness", "muscle_gain", "mobility"], focus: ["glutes", "core"], category: "strength",
    frames: [
      { pelvis: [200, 262], torso: 164, head: 172, armN: [0, 0], legN: [42, 282, 345] },
      { pelvis: [200, 262], torso: 164, head: 172, armN: [0, 0], legN: [42, 282, 345], legF: [78, 5, 30] },
    ],
    desc: "Hold a glute bridge and alternate lifting each foot, challenging hip stability and core control with no impact.",
    tips: ["Keep your hips level as a foot lifts.", "Squeeze the glutes the whole time."],
    instructions: ["Lie on your back with your knees bent and lift into a glute bridge.", "Keeping your hips level, lift one foot off the floor.", "Place it down and lift the other foot.", "March for 20 to 30 seconds, then lower."],
    instructionsTr: ["Sırtüstü uzan, dizlerin bükülü; kalçayı kaldırıp köprü yap.", "Kalçanı düz tutarak bir ayağını yerden kaldır.", "Bırak ve diğer ayağı kaldır.", "20–30 saniye yürü, sonra in."],
    tipsTr: ["Ayak kalkarken kalçanı düz tut.", "Boyunca kalçanı sık."],
    descTr: "Kalça köprüsünde kalıp ayakları sırayla kaldırmak: darbesiz biçimde kalça stabilitesini ve karın kontrolünü zorlar.",
  },
];
