// Pilates (mat) — 14 hareket. Açılar: bkz. figure.mjs. Metinler Hedefit'e özgü, kısa ve güvenli ifadelerle yazıldı.
const SUP = { pelvis: [200, 300], torso: 180, head: 180 };
const sup = (o) => ({ ...SUP, ...o });
const SIT = { pelvis: [200, 300], torso: 90, head: 90 };
const sit = (o) => ({ ...SIT, ...o });

export const pilates = [
  {
    id: "wl-pilates-hundred", name: "Pilates Hundred", nameTr: "Pilates Hundred", modality: ["pilates"], sub: ["core", "full_body"], level: "intermediate", impact: "low",
    equipment: null, bodyPart: "core", primary: ["rectus_abdominis", "transverse_abdominis"], secondary: ["hip_flexors"], force: "static", mechanic: "compound", met: 3.5,
    goals: ["general_fitness", "endurance", "mobility"], focus: ["core"],
    frames: [sup({ armN: [0, 0], legN: [90, 0, 60] }), sup({ torso: 160, head: 148, armN: [-8, -8], legN: [45, 45, 90] })],
    desc: "A classic Pilates mat exercise: small, steady arm pulses while the head and shoulders stay lifted, building deep core endurance.",
    tips: ["Keep your lower back heavy on the mat; raise the legs higher if it lifts.", "Breathe in for 5 pulses and out for 5."],
    instructions: ["Lie on your back with your knees bent over your hips and your arms long by your sides.", "Exhale and curl your head and shoulders off the mat, extending the legs to about 45 degrees.", "Pulse your arms briskly up and down by your hips while breathing in for five pulses and out for five.", "Repeat for ten rounds, then lower down and hug your knees."],
    instructionsTr: ["Sırtüstü uzan; dizlerin kalçalarının üzerinde bükülü, kolların yanında uzun dursun.", "Nefes ver, baş ve omuzlarını minderden kaldır ve bacaklarını yaklaşık 45 dereceye uzat.", "Kollarınla kalçanın yanında hızlı ve küçük vuruşlar yap; beş vuruş nefes al, beş vuruş nefes ver.", "On tur tekrarla, sonra yavaşça in ve dizlerini göğsüne çek."],
    tipsTr: ["Belini minderde ağır tut; kalkıyorsa bacaklarını daha yukarıda tut.", "Beş vuruşta nefes al, beş vuruşta ver."],
    descTr: "Klasik bir Pilates minder egzersizi: baş ve omuzlar havadayken küçük, düzenli kol vuruşlarıyla derin karın dayanıklılığını geliştirir.",
  },
  {
    id: "wl-pilates-roll-up", name: "Pilates Roll-Up", nameTr: "Pilates Roll-Up", modality: ["pilates"], sub: ["core", "full_body"], level: "intermediate", impact: "low",
    equipment: null, bodyPart: "core", primary: ["rectus_abdominis"], secondary: ["hip_flexors", "erector_spinae"], force: "dynamic", mechanic: "compound", met: 3.5,
    goals: ["general_fitness", "mobility", "muscle_gain"], focus: ["core"],
    frames: [sup({ armN: [180, 180], legN: [0, 0, 90] }), sit({ torso: 52, head: 46, armN: [8, 8], legN: [0, 0, 90] })],
    desc: "A slow, articulated sit-up that rolls the spine up one segment at a time and folds over the legs.",
    tips: ["Press your heels away and keep your feet active.", "If you stick, bend your knees or use a strap."],
    instructions: ["Lie on your back with your legs long and your arms overhead.", "Inhale to lift your arms to the ceiling, then exhale and curl your chin to your chest.", "Roll up one vertebra at a time and reach over your legs.", "Inhale at the top, then exhale and roll back down slowly."],
    instructionsTr: ["Sırtüstü uzan; bacakların uzun, kolların başının üstünde olsun.", "Nefes alırken kollarını tavana kaldır, nefes verirken çeneni göğsüne yaklaştır.", "Omurgayı parça parça kaldırarak bacaklarının üzerine uzan.", "Tepede nefes al, nefes verirken yavaşça geri yuvarlan."],
    tipsTr: ["Topuklarını uzağa it, ayaklarını aktif tut.", "Takılırsan dizlerini bük ya da bir bant kullan."],
    descTr: "Omurgayı bir bir kaldırıp bacakların üzerine katlanan, yavaş ve kontrollü bir otur-kalk hareketi.",
  },
  {
    id: "wl-pilates-single-leg-stretch", name: "Pilates Single Leg Stretch", nameTr: "Pilates Tek Bacak Esneme", modality: ["pilates"], sub: ["core", "beginner"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "core", primary: ["rectus_abdominis", "obliques"], secondary: ["hip_flexors"], force: "dynamic", mechanic: "compound", met: 3.5,
    goals: ["general_fitness", "endurance"], focus: ["core"],
    frames: [sup({ torso: 162, head: 150, armN: [75, 15], legN: [72, 12, 80], legF: [38, 38, 90] }), sup({ torso: 162, head: 150, armN: [75, 15], legN: [38, 38, 90], legF: [72, 12, 80] })],
    desc: "Alternating knee hugs with the head and shoulders lifted; trains coordination and abdominal control.",
    tips: ["Keep your pelvis still while the legs switch.", "Lower your head if your neck tires."],
    instructions: ["Lie on your back, lift your head and shoulders, and draw one knee in with your hands on that shin.", "Extend the other leg long at about 45 degrees.", "Switch legs smoothly, exhaling as you change.", "Continue for 10 to 16 switches, keeping the lower back steady."],
    instructionsTr: ["Sırtüstü uzan, baş ve omuzlarını kaldır; bir dizini çekip ellerini o kaval kemiğine koy.", "Diğer bacağını yaklaşık 45 derece uzun uzat.", "Bacakları akıcı biçimde değiştir; her değişimde nefes ver.", "10–16 değişim yap, beli sabit tut."],
    tipsTr: ["Bacaklar değişirken kalçanı sabit tut.", "Boynun yorulursa başını indir."],
    descTr: "Baş ve omuzlar havadayken dizleri sırayla çekmek; koordinasyonu ve karın kontrolünü geliştirir.",
  },
  {
    id: "wl-pilates-double-leg-stretch", name: "Pilates Double Leg Stretch", nameTr: "Pilates Çift Bacak Esneme", modality: ["pilates"], sub: ["core", "full_body"], level: "intermediate", impact: "low",
    equipment: null, bodyPart: "core", primary: ["rectus_abdominis", "transverse_abdominis"], secondary: ["hip_flexors", "anterior_deltoid"], force: "dynamic", mechanic: "compound", met: 3.5,
    goals: ["general_fitness", "endurance"], focus: ["core"],
    frames: [sup({ torso: 158, head: 146, armN: [70, 25], legN: [78, 22, 40] }), sup({ torso: 162, head: 152, armN: [160, 160], legN: [40, 40, 90] })],
    desc: "Open and close the body: knees hug in, then arms and legs reach away together while the abdominals stay lifted.",
    tips: ["Reach long, not high; keep the lower back anchored.", "Move with your breath: out as you extend, in as you hug."],
    instructions: ["Lie on your back with your head and shoulders lifted and your knees hugged to your chest.", "Inhale and reach your arms overhead while straightening the legs to about 45 degrees.", "Exhale and sweep your arms in a circle, pulling your knees back to your chest.", "Repeat for eight to ten rounds."],
    instructionsTr: ["Sırtüstü uzan, baş ve omuzların havada, dizlerin göğsüne çekili olsun.", "Nefes al; kollarını başının üstüne uzatırken bacaklarını yaklaşık 45 dereceye düzelt.", "Nefes ver; kollarınla geniş bir daire çizip dizlerini göğsüne çek.", "Sekiz–on tur tekrarla."],
    tipsTr: ["Yukarı değil uzağa uzan; beli sabit tut.", "Nefesle hareket et: uzanırken ver, çekerken al."],
    descTr: "Vücudu aç-kapa: dizler göğse çekilir, sonra kollar ve bacaklar birlikte uzanır; karın sürekli aktif kalır.",
  },
  {
    id: "wl-pilates-shoulder-bridge", name: "Pilates Shoulder Bridge", nameTr: "Pilates Omuz Köprüsü", modality: ["pilates"], sub: ["beginner", "lower_body", "posture"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "upper_legs", primary: ["gluteus_maximus", "hamstrings"], secondary: ["erector_spinae", "rectus_abdominis"], force: "push", mechanic: "compound", met: 3.5,
    goals: ["general_fitness", "muscle_gain", "mobility"], focus: ["glutes"],
    frames: [sup({ pelvis: [200, 322], armN: [0, 0], legN: [62, 282, 345] }), sup({ pelvis: [200, 262], torso: 164, head: 172, armN: [0, 0], legN: [42, 282, 345] })],
    desc: "Peel the spine off the mat to lift the hips, then lower slowly: strengthens glutes and hamstrings and mobilises the spine.",
    tips: ["Press through your whole foot, not only the toes.", "Stop where your ribs and hips form a straight line."],
    instructions: ["Lie on your back with your knees bent and your feet hip-width apart.", "Exhale and tilt your pelvis, then lift your hips one vertebra at a time.", "Pause with a long line from knees to shoulders.", "Inhale, then roll down slowly from the upper back to the tailbone."],
    instructionsTr: ["Sırtüstü uzan; dizlerin bükülü, ayakların kalça genişliğinde olsun.", "Nefes ver, pelvisini yatır ve kalçanı omurga omurga kaldır.", "Dizlerden omuzlara uzun, düz bir çizgi oluşturup bir an dur.", "Nefes al ve üst sırttan kuyruk sokumuna doğru yavaşça in."],
    tipsTr: ["Yalnızca parmak uçlarına değil, ayağın tamamına bas.", "Kaburga ve kalçan düz bir çizgi olunca dur."],
    descTr: "Omurgayı minderden kaldırarak kalçayı yükseltmek ve yavaşça indirmek: kalça ve arka bacağı güçlendirir, omurgayı mobilize eder.",
  },
  {
    id: "wl-pilates-swimming", name: "Pilates Swimming", nameTr: "Pilates Yüzme", modality: ["pilates"], sub: ["posture", "full_body"], level: "intermediate", impact: "low",
    equipment: null, bodyPart: "back", primary: ["erector_spinae", "gluteus_maximus"], secondary: ["posterior_deltoid", "hamstrings"], force: "dynamic", mechanic: "compound", met: 3.5,
    goals: ["general_fitness", "mobility", "endurance"], focus: ["back", "glutes"],
    frames: [
      { pelvis: [200, 300], torso: 6, head: 14, armN: [16, 16], armF: [0, 0], legN: [180, 180, 270], legF: [192, 192, 270] },
      { pelvis: [200, 300], torso: 6, head: 14, armN: [0, 0], armF: [16, 16], legN: [192, 192, 270], legF: [180, 180, 270] },
    ],
    desc: "Lying face down, flutter opposite arm and leg while the back stays long; builds posture muscles along the spine.",
    tips: ["Keep your neck long, gaze at the mat.", "Draw your navel in lightly to protect the lower back."],
    instructions: ["Lie face down with your arms reaching forward and your legs long.", "Lift your head, chest and limbs slightly off the mat.", "Flutter opposite arm and leg up and down in small, quick beats while breathing steadily.", "Continue for 20 to 30 seconds, then rest."],
    instructionsTr: ["Yüzüstü uzan; kolların öne uzanmış, bacakların uzun olsun.", "Baş, göğüs ve uzuvlarını minderden hafifçe kaldır.", "Çapraz kol ve bacağı küçük ve hızlı vuruşlarla yukarı aşağı oynat; nefesini düzenli tut.", "20–30 saniye devam et, sonra dinlen."],
    tipsTr: ["Boynunu uzun tut, bakışın minderde olsun.", "Belini korumak için göbeğini hafifçe içeri çek."],
    descTr: "Yüzüstü, çapraz kol ve bacağı çırparken sırt uzun kalır; omurga boyunca duruş kaslarını geliştirir.",
  },
  {
    id: "wl-pilates-swan-prep", name: "Pilates Swan Prep", nameTr: "Pilates Kuğu Hazırlık", modality: ["pilates"], sub: ["beginner", "upper_body", "posture"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "back", primary: ["erector_spinae"], secondary: ["posterior_deltoid", "trapezius"], force: "push", mechanic: "compound", met: 2.8,
    goals: ["general_fitness", "mobility"], focus: ["back"],
    frames: [
      { pelvis: [200, 300], torso: 3, head: 5, armN: [270, 0], armF: [270, 0], legN: [180, 180, 270] },
      { pelvis: [200, 300], torso: 28, head: 34, armN: [270, 0], armF: [270, 0], legN: [180, 180, 270] },
    ],
    desc: "A gentle prone back extension on the forearms that opens the chest and strengthens the upper back.",
    tips: ["Lengthen out of the waist rather than cranking the neck back.", "Keep your pubic bone on the mat."],
    instructions: ["Lie face down with your forearms on the mat and your elbows under your shoulders.", "Inhale and lengthen your spine forward and up, lifting your chest.", "Keep your shoulders away from your ears and your legs together.", "Exhale and lower with control. Repeat 6 to 8 times."],
    instructionsTr: ["Yüzüstü uzan; ön kolların minderde, dirsekler omuz altında olsun.", "Nefes al, omurgayı öne ve yukarı uzatarak göğsünü kaldır.", "Omuzlarını kulaklarından uzak, bacaklarını bitişik tut.", "Nefes verirken kontrolle in. 6–8 tekrar yap."],
    tipsTr: ["Boynu geriye kırmak yerine belden uzat.", "Kasık kemiğini minderde tut."],
    descTr: "Ön kollar üzerinde yapılan nazik bir sırt ekstansiyonu: göğsü açar, üst sırtı güçlendirir.",
  },
  {
    id: "wl-pilates-rolling-like-a-ball", name: "Pilates Rolling Like a Ball", nameTr: "Pilates Top Gibi Yuvarlanma", modality: ["pilates"], sub: ["core", "beginner"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "core", primary: ["rectus_abdominis"], secondary: ["erector_spinae"], force: "dynamic", mechanic: "isolation", met: 3,
    goals: ["general_fitness", "mobility"], focus: ["core"],
    frames: [
      { pelvis: [200, 300], torso: 62, head: 50, bend: 55, armN: [330, 250], legN: [95, 235, 330] },
      { pelvis: [196, 308], torso: 150, head: 130, bend: 55, armN: [300, 250], legN: [90, 225, 320] },
    ],
    desc: "Balance on your tailbone in a tight ball and roll back and forth along the spine, massaging the back and training control.",
    tips: ["Keep the ball shape; do not roll onto your neck.", "Place a folded towel under your tailbone if it is tender."],
    instructions: ["Sit and hug your shins, knees bent, chin tucked, balanced behind your sit bones.", "Inhale and roll back to your shoulder blades, keeping the round shape.", "Exhale and use your abdominals to roll back up to balance.", "Repeat 6 to 8 times without letting your feet touch down."],
    instructionsTr: ["Otur, kaval kemiklerini kucakla; dizler bükülü, çene içeride, oturma kemiklerinin gerisinde dengede dur.", "Nefes al ve yuvarlak şekli koruyarak kürek kemiklerine kadar geri yuvarlan.", "Nefes ver ve karın kaslarınla dengeye geri gel.", "Ayakların yere değmeden 6–8 tekrar yap."],
    tipsTr: ["Top şeklini koru; boynuna yuvarlanma.", "Kuyruk sokumun hassassa altına katlı bir havlu koy."],
    descTr: "Kuyruk sokumunda sıkı bir top şeklinde dengelenip omurga boyunca ileri geri yuvarlanmak: sırtı masajlar, kontrolü geliştirir.",
  },
  {
    id: "wl-pilates-teaser-prep", name: "Pilates Teaser Prep", nameTr: "Pilates Teaser Hazırlık", modality: ["pilates"], sub: ["core", "full_body"], level: "intermediate", impact: "low",
    equipment: null, bodyPart: "core", primary: ["rectus_abdominis", "transverse_abdominis"], secondary: ["hip_flexors", "quadriceps"], force: "static", mechanic: "compound", met: 3.5,
    goals: ["general_fitness", "endurance", "muscle_gain"], focus: ["core"],
    frames: [sup({ armN: [90, 90], legN: [90, 0, 60] }), sup({ torso: 128, head: 120, bend: 25, armN: [20, 20], legN: [60, 0, 60] })],
    desc: "A bent-knee V-sit that lifts the chest while the shins stay parallel to the floor; builds strong, controlled abdominals.",
    tips: ["Keep your chest open, not collapsed.", "Slow the descent as much as the rise."],
    instructions: ["Lie on your back with your knees over your hips and your shins parallel to the floor.", "Exhale and curl your head, shoulders and ribs up, reaching your hands toward your shins.", "Hold for two breaths with the back long.", "Roll down one segment at a time."],
    instructionsTr: ["Sırtüstü uzan; dizlerin kalçaların üzerinde, kaval kemiklerin yere paralel olsun.", "Nefes ver; baş, omuz ve kaburgalarını kaldırıp ellerini kaval kemiklerine uzat.", "Sırtı uzun tutarak iki nefes bekle.", "Parça parça yavaşça in."],
    tipsTr: ["Göğsünü açık tut, çökertme.", "İnişi çıkış kadar yavaş yap."],
    descTr: "Dizler bükülü V-oturuş: kaval kemikleri yere paralelken göğüs kalkar; güçlü ve kontrollü karın kasları geliştirir.",
  },
  {
    id: "wl-pilates-single-leg-circles", name: "Pilates Single Leg Circles", nameTr: "Pilates Tek Bacak Daireleri", modality: ["pilates"], sub: ["beginner", "lower_body", "core"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "upper_legs", primary: ["hip_flexors", "gluteus_medius"], secondary: ["rectus_abdominis", "adductors"], force: "dynamic", mechanic: "isolation", met: 3,
    goals: ["general_fitness", "mobility"], focus: ["hips", "core"],
    frames: [sup({ armN: [0, 0], legN: [0, 0, 90], legF: [90, 90, 90] }), sup({ armN: [0, 0], legN: [0, 0, 90], legF: [58, 58, 90] })],
    desc: "Draw small circles with one leg while the pelvis stays still; separates hip movement from the trunk.",
    tips: ["Make the circles small enough to keep the pelvis quiet.", "Bend the lifted knee slightly if the hamstring is tight."],
    instructions: ["Lie on your back with one leg extended on the mat and the other lifted toward the ceiling.", "Keep your hips level and draw a small circle with the lifted leg across the body, down, out and up.", "Complete five circles, then reverse the direction.", "Switch legs."],
    instructionsTr: ["Sırtüstü uzan; bir bacağın minderde uzun, diğeri tavana doğru kalkık olsun.", "Kalçanı sabit tutarak kalkık bacakla vücudun önünden aşağı, dışa ve yukarı küçük bir daire çiz.", "Beş daire yap, sonra yönü değiştir.", "Bacak değiştir."],
    tipsTr: ["Pelvis sakin kalsın diye daireleri küçük tut.", "Arka bacağın gergin ise kaldırdığın dizi hafif bük."],
    descTr: "Pelvis sabitken bir bacakla küçük daireler çizmek: kalça hareketini gövdeden ayırmayı öğretir.",
  },
  {
    id: "wl-pilates-toe-taps", name: "Pilates Tabletop Toe Taps", nameTr: "Pilates Masa Pozisyonu Ayak Dokunuşu", modality: ["pilates"], sub: ["beginner", "core", "short"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "core", primary: ["transverse_abdominis", "rectus_abdominis"], secondary: ["hip_flexors"], force: "dynamic", mechanic: "isolation", met: 3,
    goals: ["general_fitness", "endurance", "fat_loss"], focus: ["core"],
    frames: [sup({ armN: [0, 0], legN: [90, 0, 60], legF: [90, 0, 60] }), sup({ armN: [0, 0], legN: [90, 0, 60], legF: [68, 292, 350] })],
    desc: "From tabletop, lower one foot to tap the mat and return, keeping the ribs knit and the back still.",
    tips: ["If your back arches, tap with a smaller range.", "Move slowly, exhaling on each tap."],
    instructions: ["Lie on your back with your knees stacked over your hips, shins parallel to the floor.", "Brace gently and lower one foot toward the mat, tapping the toes.", "Return to tabletop, then repeat with the other foot.", "Alternate for 10 to 20 taps."],
    instructionsTr: ["Sırtüstü uzan; dizlerin kalçaların üzerinde, kaval kemikleri yere paralel (masa pozisyonu) olsun.", "Karnını hafifçe sık ve bir ayağını minderdeki parmak ucuna dokunana kadar indir.", "Masa pozisyonuna dön, diğer ayakla tekrarla.", "10–20 dokunuş boyunca sırayla devam et."],
    tipsTr: ["Belin kalkıyorsa daha küçük bir aralıkla dokun.", "Yavaş git, her dokunuşta nefes ver."],
    descTr: "Masa pozisyonundan bir ayağı yere dokundurup geri getirmek: kaburga kapalı, bel sabit kalır.",
  },
  {
    id: "wl-pilates-pelvic-curl", name: "Pilates Pelvic Curl", nameTr: "Pilates Pelvik Kıvrılma", modality: ["pilates"], sub: ["beginner", "recovery", "short", "posture"], level: "beginner", impact: "low",
    equipment: null, bodyPart: "core", primary: ["transverse_abdominis", "gluteus_maximus"], secondary: ["erector_spinae"], force: "dynamic", mechanic: "isolation", met: 2.5,
    goals: ["mobility", "general_fitness"], focus: ["core", "glutes"],
    frames: [sup({ pelvis: [200, 322], armN: [0, 0], legN: [62, 282, 345] }), sup({ pelvis: [200, 300], torso: 176, head: 180, bend: 12, armN: [0, 0], legN: [62, 282, 345] })],
    desc: "A small pelvic tilt that curls the tailbone toward the ceiling; a gentle spine warm-up and low-back relief.",
    tips: ["Keep the movement small and smooth.", "Relax the neck and jaw."],
    instructions: ["Lie on your back with your knees bent and your feet flat.", "Exhale and tilt your pelvis so your tailbone curls up and your lower back presses into the mat.", "Inhale to release back to a neutral spine.", "Repeat slowly 10 times."],
    instructionsTr: ["Sırtüstü uzan; dizlerin bükülü, ayakların yerde olsun.", "Nefes ver ve pelvisini yatırarak kuyruk sokumunu kıvır, belini minderde bastır.", "Nefes alarak nötr omurgaya dön.", "Yavaşça 10 kez tekrarla."],
    tipsTr: ["Hareketi küçük ve akıcı tut.", "Boyun ve çeneni gevşet."],
    descTr: "Kuyruk sokumunu tavana doğru kıvıran küçük bir pelvik eğim: nazik bir omurga ısınması ve bel rahatlatma hareketi.",
  },
];
